### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by subblue** [mattdesl/gh-readme-scrape#1]
I thought I'd give the script a quick spin with the gfx-resources example:

`gh-readme-scrape mattdesl/graphics-resources gfx-resources/ -e pdf,pptx,ppt --rename` 

but got this error:

```
Searching 114 links
Error requesting URL: http://www.amazon.ca/Math-Primer-Graphics-Development-Edition/dp/1568817231
Error requesting URL: http://www.amazon.ca/Essential-Mathematics-Games-Interactive-Applications/dp/0123742978
_http_client.js:75
    throw new Error('Protocol "' + protocol + '" not supported. ' +
          ^
Error: Protocol "https:" not supported. Expected "http:".
    at new ClientRequest (_http_client.js:75:11)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at get (/Users/tom/.nvm/versions/node/v0.12.0/lib/node_modules/gh-readme-scrape/node_modules/got/index.js:137:16)
    at ClientRequest.<anonymous> (/Users/tom/.nvm/versions/node/v0.12.0/lib/node_modules/gh-readme-scrape/node_modules/got/index.js:162:5)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:129:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_client.js:310:20)
```

thx

**Comment by mattdesl** [comment]
Hmm weird, I can't seem to reproduce it. I will poke around and see what I can do.

**Comment by mattdesl** [comment]
Hey Tom, when you run `node -v` and `npm -v` what are you getting?

There is another issue indicating this might be a problem with a particular version of node: https://github.com/TooTallNate/node-proxy-agent/issues/1

**Comment by mattdesl** [comment]
OK, I actually just bumped my Node.js version and now I'm able to reproduce. :smile: Will continue digging...

**Comment by subblue** [comment]
Yeah I'm on node 0.12.0 at the moment, but switching back to 0.10.x via NVM it works ok.

**Comment by mattdesl** [comment]
If you re-install globally it should work now. This was fixed upstream: https://github.com/sindresorhus/got/issues/80

**Comment by subblue** [comment]
Seems good now, thanks :)
